name: Deploy to FTP

on:
  push:
    branches:
      - gh-pages  # Trigger on push to gh-pages branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Upload to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Directory of your website files in the repository (root of gh-pages branch)
        server-dir: /www/  # Ensure this ends with a slash to denote a directory
